import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import NavBar from "@/components/common/NavBar";
import I18nProvider from "@/providers/I18nProvider";
import AnimatedCursor from "@/components/common/AnimatedCursor";

const pretendard = localFont({
  src: "../../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params,
  children,
}: Readonly<{
  params: { locale: string };
  children: React.ReactNode;
}>) {
  return (
    <html lang={params.locale} suppressHydrationWarning>
      <body
        className={`${pretendard.variable} min-w-[320px] break-keep font-pretendard`}
      >
        <ThemeProvider>
          <I18nProvider params={params}>
            <NavBar />

            {children}
            <AnimatedCursor />
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
